/*
 * Minecraft Engine
 * Copyright (C) 2026 TaimWay <taimway@gmail.com>
 *
 * @File: minecraft/source/index.cpp
 * @Description:
 * @Ownership: TaimWay <taimway@gmail.com> - 01/07/2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <minecraft/index.hpp>
#include <fstream>

void cnt::minecraft::Index::_init()
{
    if (!fs::exists(path))
        fs::create_directory(path);

    if (!fs::exists(path / "meic.cco"))
        _create_meic();
}

void cnt::minecraft::Index::_create_meic()
{
    std::ofstream file(path / "meic.cco");
    if (!file.is_open())
        throw std::runtime_error("Failed to open file");
    file << R"(/* Minecraft Engine Index Config (MEIC)
 *
 * This file is used to configure the runtime environment of the game. 
 * It is generated by the minecraft engine and should not be modified by the user.
 */

name: )" + path.filename().string() + R"(
lastVersion: None,
config: {
    VersionIsolation: 2, // 0: Disable, 1: Enable, 2: Global
    WindowsTitle: "${..config.WindowsTitle}", // Title of the game window
    GameInfo: "${..config.GameInfo}", // Custom game information, it will display when u press F3 in game
}.
)";
}